env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
plugins:
  - import
  - react
rules:
  comma-dangle: ['error', 'always-multiline']
  indent: [error, 2, SwitchCase: 1]
  linebreak-style: [error, unix]
  quotes: [2, single]
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/react-in-jsx-scope: 2
  semi: [error, never]
  strict: [2, never]

